apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: demo-

commonLabels:
  environment: demo

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yml
  - ingress-patch.yml
  - hpa-patch.yml
